sonar.projectKey=Ineees24_skillhub-test
sonar.organization=ineees24
sonar.projectVersion=1.0
sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

sonar.sources=skillhub-back/app,skillhub-back/routes,skillhub-back/bootstrap,skillhub-back/config,skillhub-back/database
sonar.tests=skillhub-back/tests

sonar.exclusions=**/vendor/**,**/node_modules/**,**/dist/**,**/build/**,**/storage/**,**/bootstrap/cache/**,skillhub-back/public/**

sonar.coverage.exclusions=\
  **/database/migrations/**, \
  **/database/seeders/**, \
  **/database/factories/**, \
  **/bootstrap/**, \
  **/config/**, \
  **/routes/**
  **/Services/AuthServiceClient.php

sonar.test.inclusions=skillhub-back/tests/**/*.php
sonar.php.coverage.reportPaths=skillhub-back/coverage/clover.xml